### ISSUE TITLE
Site Not available

### ISSUE THREAD

**Issue by EnderActually** [wertercatt/wertercatt.com#1]
in title

**Comment by wertercatt** [comment]
https://wertercatt.github.io/catt.htm loads fine for me. Going to close this for lacking details.

**Comment by EnderActually** [comment]
> https://wertercatt.github.io/catt.htm loads fine for me. Going to close this for lacking details.

Ah, sorry I did not specify, I can't seem to access Steam for schools

**Comment by wertercatt** [comment]
Ah. Yeah the main web server is down. Will get it back up tomorrow 🤞

**Comment by EnderActually** [comment]
Thanks

**Comment by wertercatt** [comment]
https://wertercatt.com/Steam-For-Schools/ is back up.

**Comment by EnderActually** [comment]
Thanks!
